### ISSUE TITLE
0.2.3 has a failing unit test & causes random segfaults in php-fpm

### ISSUE THREAD

**Issue by dcelasun** [chobie/php-protocolbuffers#39]
I've just tried to latest 0.2.3 from github with PHP 5.5.11. First, one of the tests fail:

```
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
ProtocolBuffersMessage extension implementation [tests/600_extension_clear.phpt]
=====================================================================
```

If I ignore this and load the extension, FPM randomly crashes every few requests with:

```
[14-Apr-2014 09:19:21] WARNING: [pool www] child 10013 exited on signal 11 (SIGSEGV - core dumped) after 1.527762 seconds from start
[14-Apr-2014 09:19:21] NOTICE: [pool www] child 10018 started
[14-Apr-2014 09:19:22] WARNING: [pool www] child 10016 exited on signal 11 (SIGSEGV - core dumped) after 0.779867 seconds from start
[14-Apr-2014 09:19:22] NOTICE: [pool www] child 10020 started
[14-Apr-2014 09:19:22] WARNING: [pool www] child 10018 exited on signal 11 (SIGSEGV - core dumped) after 0.412428 seconds from start
[14-Apr-2014 09:19:22] NOTICE: [pool www] child 10022 started
[14-Apr-2014 09:19:35] WARNING: [pool www] child 10020 exited on signal 11 (SIGSEGV - core dumped) after 13.821716 seconds from start
[14-Apr-2014 09:19:35] NOTICE: [pool www] child 10037 started
[14-Apr-2014 09:19:36] WARNING: [pool www] child 10022 exited on signal 11 (SIGSEGV - core dumped) after 14.274327 seconds from start
[14-Apr-2014 09:19:36] NOTICE: [pool www] child 10040 started
[14-Apr-2014 09:19:36] WARNING: [pool www] child 10037 exited on signal 11 (SIGSEGV - core dumped) after 0.863197 seconds from start
[14-Apr-2014 09:19:36] NOTICE: [pool www] child 10042 started
[14-Apr-2014 09:19:37] WARNING: [pool www] child 10040 exited on signal 11 (SIGSEGV - core dumped) after 0.456663 seconds from start
```

There are also several warnings during make:

```
/tmp/php-protocolbuffers/json_serializer.c:353:3: warning: passing argument 4 of ‘add_assoc_stringl_ex’ discards ‘const’ qualifier from pointer target type [enabled by default]
   add_assoc_stringl_ex(result, scheme->original_name, scheme->original_name_len, value, value_len, 1);
   ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /tmp/php-protocolbuffers/php_protocolbuffers.h:41,
                 from /tmp/php-protocolbuffers/protocolbuffers.h:34,
                 from /tmp/php-protocolbuffers/json_serializer.c:1:
/usr/include/php/Zend/zend_API.h:382:14: note: expected ‘char *’ but argument is of type ‘const char *’
 ZEND_API int add_assoc_stringl_ex(zval *arg, const char *key, uint key_len, char *str, uint length, int duplicate);
              ^
/tmp/php-protocolbuffers/json_serializer.c: At top level:
/tmp/php-protocolbuffers/json_serializer.c:388:2: warning: initialization from incompatible pointer type [enabled by default]
  _json_serializer_fixed64,//fixed64
  ^
/tmp/php-protocolbuffers/json_serializer.c:388:2: warning: (near initialization for ‘json_serializer.serialize_fixed64’) [enabled by default]
/tmp/php-protocolbuffers/json_serializer.c: In function ‘php_protocolbuffers_json_encode_value’:
/tmp/php-protocolbuffers/json_serializer.c:637:4: warning: passing argument 2 of ‘convert_to_int64’ from incompatible pointer type [enabled by default]
    convert_to_int64(&value_copy, &v);
    ^
/tmp/php-protocolbuffers/json_serializer.c:421:12: note: expected ‘int64_t *’ but argument is of type ‘int32_t *’
 static int convert_to_int64(zval *value, int64_t *result)
            ^
/tmp/php-protocolbuffers/json_serializer.c: In function ‘php_protocolbuffers_json_encode_element’:
/tmp/php-protocolbuffers/json_serializer.c:687:2: warning: passing argument 3 of ‘php_protocolbuffers_get_property_name’ from incompatible pointer type [enabled by default]
  name = php_protocolbuffers_get_property_name(container, scheme, &name_len);
  ^
/tmp/php-protocolbuffers/json_serializer.c:406:20: note: expected ‘size_t *’ but argument is of type ‘int *’
 static const char* php_protocolbuffers_get_property_name(php_protocolbuffers_scheme_container *container, php_protocolbuffers_scheme *scheme, size_t *name_len)
                    ^
/tmp/php-protocolbuffers/json_serializer.c:687:7: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  name = php_protocolbuffers_get_property_name(container, scheme, &name_len);
       ^
```

**Comment by dcelasun** [comment]
In the meantime, I've reverted back to [this](https://github.com/chobie/php-protocolbuffers/commit/09e0934f47996a2b19f3e049244bcb9ed9a97c81) commit to get a stable build.

**Comment by chobie** [comment]
hmm, let me look into this.

**Comment by chobie** [comment]
I'm sorry for this issue. I've missed implementations. I'll add non-cli test case for prevent this kind of mistakes.

**Comment by chobie** [comment]
hmm, still failed on centos machine. I'm look into deeper.

**Comment by chobie** [comment]
I've fixed problem. just released v0.2.5. 

[problems]
- a)  missed jsonSerialize implementation.
  - i'll add non-cli test case for prevent this kind of problems.
- b) miss matched type size (`int` is different from `size_t` on some environment. like CentOS 64bit). 
  - I'll setup CentOS CI.

I am sorry about these issues.

**Comment by dcelasun** [comment]
Thanks! `tests/600_extension_clear.phpt` is still failing during `make test`, but the segfaults are gone.

> I am sorry about these issues.

No worries, thanks for fixing these so fast :)

**Comment by chobie** [comment]
released v0.2.6.
- fixes `600_extension_clear.phpt` test case
- fixes several compile warnings (thanks remi)

probably this issue solved. could you check v0.2.6 release when you have a chance?

**Comment by dcelasun** [comment]
I'll do more tests when I get to work in a few hours, but a quick test on my laptop shows no build warnings, no failing tests and no segfaults. Thanks!

**Comment by dcelasun** [comment]
Just tested on CentOS 6.5 and everything works fine. I'm closing this issue.

**Comment by chobie** [comment]
thank you!
